# base image that we will be adding more stuff to
# FROM nginx:latest
FROM nginx:alpine

# add all the files in current directory (where Dockerfile is in) to the nginx/html directory
# add <source> <destination>
ADD . /usr/share/nginx/html


